/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    
    int e=1;
    
    
    public Help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Queue = new javax.swing.JLabel();
        CL = new javax.swing.JLabel();
        CB = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Queue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QueueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QueueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QueueMouseExited(evt);
            }
        });
        getContentPane().add(Queue, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 290, 250));

        CL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CLMouseExited(evt);
            }
        });
        getContentPane().add(CL, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 290, 250));

        CB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CBMouseExited(evt);
            }
        });
        getContentPane().add(CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 290, 250));

        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 80));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/Help.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 772));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        if(e==1){
        this.setVisible(false);
        }
        else{
            ImageIcon IZ = new ImageIcon(getClass().getResource("/ImageBackground/Help.png"));
            BG.setIcon(IZ);
            
            e=1;
        }
    }//GEN-LAST:event_ExitMouseClicked

    private void CBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBMouseClicked
        if(e==1){
        ImageIcon IZ = new ImageIcon(getClass().getResource("/ImageBackground/Help1-1.png"));
        BG.setIcon(IZ);
        
        e=2;
        }
        
    }//GEN-LAST:event_CBMouseClicked

    private void QueueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueueMouseClicked
        if(e==1){
        ImageIcon IL = new ImageIcon(getClass().getResource("/ImageBackground/Help3-3.png"));
        BG.setIcon(IL);
        
        e=2;
        }
    }//GEN-LAST:event_QueueMouseClicked

    private void CLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLMouseClicked
        if(e==1){
        ImageIcon IQ = new ImageIcon(getClass().getResource("/ImageBackground/Help2-2.png"));
        BG.setIcon(IQ);
        
        e=2;
        }
    }//GEN-LAST:event_CLMouseClicked

    private void CBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBMouseEntered
        if(e==1){
        ImageIcon IZ = new ImageIcon(getClass().getResource("/ImageBackground/Help1.png"));
        BG.setIcon(IZ);
        }
    }//GEN-LAST:event_CBMouseEntered

    private void CBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBMouseExited
        if(e==1){
        ImageIcon IZ = new ImageIcon(getClass().getResource("/ImageBackground/Help.png"));
        BG.setIcon(IZ);
        }
    }//GEN-LAST:event_CBMouseExited

    private void CLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLMouseEntered
        if(e==1){
        ImageIcon IZ = new ImageIcon(getClass().getResource("/ImageBackground/Help2.png"));
        BG.setIcon(IZ);
        }
    }//GEN-LAST:event_CLMouseEntered

    private void CLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLMouseExited
        if(e==1){
        ImageIcon IZ = new ImageIcon(getClass().getResource("/ImageBackground/Help.png"));
        BG.setIcon(IZ);
        }
    }//GEN-LAST:event_CLMouseExited

    private void QueueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueueMouseEntered
        if(e==1){
        ImageIcon IZ = new ImageIcon(getClass().getResource("/ImageBackground/Help3.png"));
        BG.setIcon(IZ);
        }
    }//GEN-LAST:event_QueueMouseEntered

    private void QueueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueueMouseExited
        if(e==1){
        ImageIcon IZ = new ImageIcon(getClass().getResource("/ImageBackground/Help.png"));
        BG.setIcon(IZ);
        }
    }//GEN-LAST:event_QueueMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel CB;
    private javax.swing.JLabel CL;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Queue;
    // End of variables declaration//GEN-END:variables
}
