/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.ImageIcon;
import AppPackage.AnimationClass;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Kelompok Queue
 */
public class Queue1 extends javax.swing.JFrame {
    int antrianTerakhir;
    int xMouse;
    int yMouse;
    int t=1;
    int B=2;
    int Bg = 1;
    int s=1;
    int K=1;
    private Timer z;
    private int count = 0;
    private Queue rs = new Queue();
    
    
    public Queue1() {
        initComponents();
        antrianTerakhir = 1;
        this.setLocation(400, 100);
        txtNoDaftar.setText(String.valueOf(antrianTerakhir));
        lblPanggilNomor1.setVisible(false);
        lblPanggilNomor2.setVisible(false);
        lblPanggilNomor3.setVisible(false);
        lblPanggilNama1.setVisible(false);
        lblPanggilNama2.setVisible(false);
        lblPanggilNama3.setVisible(false);
        lblPanggilAlamat1.setVisible(false);
        lblPanggilAlamat2.setVisible(false);
        lblPanggilAlamat3.setVisible(false);
        BtnLoket1.setVisible(false);
        BtnLoket2.setVisible(false);
        BtnLoket3.setVisible(false);
        Loket1.setVisible(false);
        Loket2.setVisible(false);
        Loket3.setVisible(false);
        BackRahasia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel7 = new javax.swing.JLabel();
        BG1 = new javax.swing.JLabel();
        BG2 = new javax.swing.JLabel();
        BG3 = new javax.swing.JLabel();
        BG4 = new javax.swing.JLabel();
        BG5 = new javax.swing.JLabel();
        INA = new javax.swing.JLabel();
        ENG = new javax.swing.JLabel();
        Kembali = new javax.swing.JLabel();
        ChangeBackground = new javax.swing.JLabel();
        ChangeLanguage = new javax.swing.JLabel();
        Temp = new javax.swing.JLabel();
        Help = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        Setting = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JLabel();
        BackgroundBtn = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BackgroundTop = new javax.swing.JLabel();
        BackRahasia = new javax.swing.JLabel();
        lblPanggilNomor2 = new javax.swing.JLabel();
        lblPanggilNama2 = new javax.swing.JLabel();
        lblPanggilAlamat2 = new javax.swing.JLabel();
        lblPanggilNomor3 = new javax.swing.JLabel();
        lblPanggilNama3 = new javax.swing.JLabel();
        lblPanggilAlamat3 = new javax.swing.JLabel();
        lblPanggilNomor1 = new javax.swing.JLabel();
        lblPanggilNama1 = new javax.swing.JLabel();
        lblPanggilAlamat1 = new javax.swing.JLabel();
        BtnLoket1 = new javax.swing.JLabel();
        BtnLoket2 = new javax.swing.JLabel();
        BtnLoket3 = new javax.swing.JLabel();
        Loket3 = new javax.swing.JLabel();
        Loket2 = new javax.swing.JLabel();
        Loket1 = new javax.swing.JLabel();
        Ayo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        Kosong = new javax.swing.JLabel();
        Daftar = new javax.swing.JLabel();
        txtNoDaftar = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        ToList2 = new javax.swing.JLabel();
        ToList = new javax.swing.JLabel();
        ToLoket = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAntrian2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAntrian1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAntrian = new javax.swing.JTable();
        Background = new javax.swing.JLabel();
        BackgroundBgt = new javax.swing.JLabel();
        BackgroundBgt2 = new javax.swing.JLabel();
        BackgroundAja = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 772));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1160, 772));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/BGutama1INA.png"))); // NOI18N
        BG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BG1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BG1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BG1MouseExited(evt);
            }
        });
        getContentPane().add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -100, 500, 100));

        BG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/Dad1INA.png"))); // NOI18N
        BG2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BG2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BG2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BG2MouseExited(evt);
            }
        });
        getContentPane().add(BG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -100, 500, 100));

        BG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/Alam1INA.png"))); // NOI18N
        BG3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BG3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BG3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BG3MouseExited(evt);
            }
        });
        getContentPane().add(BG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -100, 500, 100));

        BG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/BalonUdara1INA.png"))); // NOI18N
        BG4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BG4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BG4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BG4MouseExited(evt);
            }
        });
        getContentPane().add(BG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -100, 500, 100));

        BG5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/Cake1INA.png"))); // NOI18N
        BG5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BG5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BG5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BG5MouseExited(evt);
            }
        });
        getContentPane().add(BG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -100, 500, 100));

        INA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/Indonesia1.png"))); // NOI18N
        INA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                INAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                INAMouseExited(evt);
            }
        });
        getContentPane().add(INA, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, -300, 400, 300));

        ENG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/Inggris1.png"))); // NOI18N
        ENG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ENGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ENGMouseExited(evt);
            }
        });
        getContentPane().add(ENG, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, -300, 400, 300));

        Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Kembali1.png"))); // NOI18N
        Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KembaliMouseExited(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -60, 60, 60));

        ChangeBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/GantiLatarBelakang1.png"))); // NOI18N
        ChangeBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeBackgroundMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangeBackgroundMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangeBackgroundMouseExited(evt);
            }
        });
        getContentPane().add(ChangeBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 0, 400, 300));

        ChangeLanguage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/GantiBahasa1.png"))); // NOI18N
        ChangeLanguage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeLanguageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangeLanguageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangeLanguageMouseExited(evt);
            }
        });
        getContentPane().add(ChangeLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 300, 400, 300));

        Temp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/White.png"))); // NOI18N
        getContentPane().add(Temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, 800, 600));

        Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Bantuan1.png"))); // NOI18N
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HelpMouseExited(evt);
            }
        });
        getContentPane().add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -775, 400, 60));

        About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Tentang1.png"))); // NOI18N
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
        });
        getContentPane().add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -775, 400, 60));

        Contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Kontak1.png"))); // NOI18N
        Contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContactMouseExited(evt);
            }
        });
        getContentPane().add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -775, 400, 60));

        Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Pengaturan1.png"))); // NOI18N
        Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingMouseExited(evt);
            }
        });
        getContentPane().add(Setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -775, 400, 60));

        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Keluar1.png"))); // NOI18N
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnMouseExited(evt);
            }
        });
        getContentPane().add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, -775, 110, 30));

        BackgroundBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/BtnMenu.png"))); // NOI18N
        BackgroundBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackgroundBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackgroundBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackgroundBtnMouseExited(evt);
            }
        });
        getContentPane().add(BackgroundBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 50, 30));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/MenuBg.png"))); // NOI18N
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -775, 1160, 775));

        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 30));

        BackgroundTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/MenuButton.png"))); // NOI18N
        getContentPane().add(BackgroundTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 860, 30));

        BackRahasia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Back.png"))); // NOI18N
        BackRahasia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackRahasia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackRahasiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackRahasiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackRahasiaMouseExited(evt);
            }
        });
        getContentPane().add(BackRahasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 70));

        lblPanggilNomor2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPanggilNomor2.setText(".....");
        getContentPane().add(lblPanggilNomor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 220, 40));

        lblPanggilNama2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPanggilNama2.setText(".....");
        getContentPane().add(lblPanggilNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 220, 40));

        lblPanggilAlamat2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPanggilAlamat2.setText(".....");
        getContentPane().add(lblPanggilAlamat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 220, 40));

        lblPanggilNomor3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPanggilNomor3.setText(".....");
        getContentPane().add(lblPanggilNomor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 220, 40));

        lblPanggilNama3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPanggilNama3.setText(".....");
        getContentPane().add(lblPanggilNama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 220, 40));

        lblPanggilAlamat3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPanggilAlamat3.setText(".....");
        getContentPane().add(lblPanggilAlamat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 220, 40));

        lblPanggilNomor1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPanggilNomor1.setText(".....");
        getContentPane().add(lblPanggilNomor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 220, 40));

        lblPanggilNama1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPanggilNama1.setText(".....");
        getContentPane().add(lblPanggilNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 471, 220, 40));

        lblPanggilAlamat1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPanggilAlamat1.setText(".....");
        getContentPane().add(lblPanggilAlamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 220, 40));

        BtnLoket1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLoket1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLoket1MouseEntered(evt);
            }
        });
        getContentPane().add(BtnLoket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, 200, 50));

        BtnLoket2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLoket2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLoket2MouseEntered(evt);
            }
        });
        getContentPane().add(BtnLoket2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 690, 200, 40));

        BtnLoket3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLoket3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLoket3MouseEntered(evt);
            }
        });
        getContentPane().add(BtnLoket3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 690, 200, 40));

        Loket3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Loket3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Loket3MouseExited(evt);
            }
        });
        getContentPane().add(Loket3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 260, 590));

        Loket2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Loket2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Loket2MouseExited(evt);
            }
        });
        getContentPane().add(Loket2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 250, 590));

        Loket1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Loket1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Loket1MouseExited(evt);
            }
        });
        getContentPane().add(Loket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 260, 590));

        Ayo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Mulai.png"))); // NOI18N
        Ayo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AyoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AyoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AyoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AyoMousePressed(evt);
            }
        });
        getContentPane().add(Ayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 300, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Mengantri.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 360, 130));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Back.png"))); // NOI18N
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 965, 70, 70));

        Kosong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Kosong.png"))); // NOI18N
        Kosong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KosongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KosongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KosongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KosongMousePressed(evt);
            }
        });
        getContentPane().add(Kosong, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1305, 90, 30));

        Daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/BtnDaftar.png"))); // NOI18N
        Daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DaftarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DaftarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DaftarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DaftarMousePressed(evt);
            }
        });
        getContentPane().add(Daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1295, -1, 50));

        txtNoDaftar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtNoDaftar.setForeground(new java.awt.Color(255, 255, 255));
        txtNoDaftar.setBorder(null);
        txtNoDaftar.setOpaque(false);
        txtNoDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(txtNoDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 1075, 340, 40));

        txtNama.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setBorder(null);
        txtNama.setOpaque(false);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 1145, 340, 40));

        txtAlamat.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamat.setBorder(null);
        txtAlamat.setOpaque(false);
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 1215, 340, 40));

        ToList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToList2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ToList2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ToList2MouseExited(evt);
            }
        });
        getContentPane().add(ToList2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1425, 120, 110));

        ToList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/BtnToList.png"))); // NOI18N
        ToList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ToListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ToListMouseExited(evt);
            }
        });
        getContentPane().add(ToList, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1285, 600, 260));

        ToLoket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/ToLoket.png"))); // NOI18N
        ToLoket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToLoketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ToLoketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ToLoketMouseExited(evt);
            }
        });
        getContentPane().add(ToLoket, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 795, -1, 70));

        tbAntrian2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tbAntrian2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbAntrian2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1620, 390, 503));

        tbAntrian1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tbAntrian1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbAntrian1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 1620, 250, 503));

        tbAntrian.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tbAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAntrian);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 1620, 120, 503));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/BGutama.png"))); // NOI18N
        Background.setAlignmentY(0.0F);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 772));

        BackgroundBgt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/DaftarTemp.png"))); // NOI18N
        BackgroundBgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackgroundBgtMouseClicked(evt);
            }
        });
        getContentPane().add(BackgroundBgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 775, 1160, 775));

        BackgroundBgt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/Artboard 1.png"))); // NOI18N
        getContentPane().add(BackgroundBgt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 775, 1160, 775));

        BackgroundAja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/List.png"))); // NOI18N
        getContentPane().add(BackgroundAja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 775, 1160, 775));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/Artboard 1.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 775));

        setBounds(0, 0, 1160, 773);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoDaftarActionPerformed
        
    // TODO add your handling code here:
    }//GEN-LAST:event_txtNoDaftarActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel9MouseDragged

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        
    }//GEN-LAST:event_jLabel9MouseEntered

    private void DaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarMouseClicked

        try {
            String nama = txtNama.getText();
            String alamat = txtAlamat.getText();
            String no = txtNoDaftar.getText();
            rs.enqueue(antrianTerakhir, nama, alamat, 0);
            updateTable();
            updateTable2();
            updateTable3();
            antrianTerakhir++;
            txtNoDaftar.setText(String.valueOf(antrianTerakhir));
            JavaMailUtil.sendMail(alamat, nama, no);
            if(B==1){
                ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnRegister3.png"));
                Daftar.setIcon(II);
            }
            else if(B==2){
                ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnDaftar3.png"));   
                Daftar.setIcon(II);
            }
        } catch (Exception ex) {
            Logger.getLogger(Queue1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DaftarMouseClicked

    private void DaftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarMouseEntered
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnRegister2.png"));
        Daftar.setIcon(II);
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnDaftar2.png"));
        Daftar.setIcon(II);
    }
    }//GEN-LAST:event_DaftarMouseEntered

    private void DaftarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarMouseExited
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnRegister.png"));
        Daftar.setIcon(II);
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnDaftar.png"));
        Daftar.setIcon(II);
    }
    }//GEN-LAST:event_DaftarMouseExited

    private void DaftarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarMousePressed
        
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnRegister2.png"));
        Daftar.setIcon(II);
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnDaftar2.png"));
        Daftar.setIcon(II);
    }
    }//GEN-LAST:event_DaftarMousePressed

    private void KosongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KosongMouseClicked
      
       txtNama.setText("");
       txtAlamat.setText("");
       if(B==1){
       ImageIcon II = new ImageIcon(getClass().getResource("/Button/Delete3.png"));
        Kosong.setIcon(II);    
       }
       else if(B==2){
       ImageIcon II = new ImageIcon(getClass().getResource("/Button/Kosong3.png"));
        Kosong.setIcon(II);
       }
    }//GEN-LAST:event_KosongMouseClicked

    private void KosongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KosongMouseEntered
        
        if(B==1){
       ImageIcon II = new ImageIcon(getClass().getResource("/Button/Delete2.png"));
        Kosong.setIcon(II);    
       }
       else if(B==2){
       ImageIcon II = new ImageIcon(getClass().getResource("/Button/Kosong2.png"));
        Kosong.setIcon(II);
       }
    }//GEN-LAST:event_KosongMouseEntered

    private void KosongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KosongMouseExited
        
        if(B==1){
       ImageIcon II = new ImageIcon(getClass().getResource("/Button/Delete.png"));
        Kosong.setIcon(II);    
       }
       else if(B==2){
       ImageIcon II = new ImageIcon(getClass().getResource("/Button/Kosong.png"));
        Kosong.setIcon(II);
       }
    }//GEN-LAST:event_KosongMouseExited

    private void KosongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KosongMousePressed
        if(B==1){
       ImageIcon II = new ImageIcon(getClass().getResource("/Button/Delete2.png"));
        Kosong.setIcon(II);    
       }
       else if(B==2){
       ImageIcon II = new ImageIcon(getClass().getResource("/Button/Kosong2.png"));
        Kosong.setIcon(II);
       }
    }//GEN-LAST:event_KosongMousePressed

    private void AyoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyoMouseClicked
      AnimationClass move = new AnimationClass();
      //Move Tampilan Utama
      move.jLabelYUp(Background.getY(), -775, 1, 5, Background);
      move.jLabelYUp(Ayo.getY(), -485, 1, 5, Ayo);
      move.jLabelYUp(jLabel10.getY(), -585, 1, 5, jLabel10);
      move.jLabelYUp(Background.getY(), -775, 1, 5, Background);
      BackgroundBtn.setLocation(550, -100);
      BG.setLocation(0, 775);
      BackgroundTop.setLocation(150, -100);
      
      //Move Tampilan 2
      move.jLabelYUp(BackgroundBgt.getY(), 0, 1, 5, BackgroundBgt);
      move.jLabelYUp(BackgroundBgt2.getY(), 0, 1, 5, BackgroundBgt2);
      move.jLabelYUp(ToList.getY(), 510, 1, 5, ToList);
      move.jLabelYUp(ToList2.getY(), 650, 1, 5, ToList2);
      move.jLabelYUp(Back.getY(), 190, 1, 5, Back);
      move.jLabelYUp(Kosong.getY(), 530, 1, 5, Kosong);
      move.jLabelYUp(Daftar.getY(), 520, 1, 5, Daftar);
      move.jTextFieldYUp(txtNoDaftar.getY(), 300, 1, 5, txtNoDaftar);
      move.jTextFieldYUp(txtNama.getY(), 370, 1, 5, txtNama);
      move.jTextFieldYUp(txtAlamat.getY(), 440, 1, 5, txtAlamat);
        
    }//GEN-LAST:event_AyoMouseClicked

    private void AyoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyoMouseEntered
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Start2.png"));
        Ayo.setIcon(II);    
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Mulai2.png"));
        Ayo.setIcon(II);
        }
    }//GEN-LAST:event_AyoMouseEntered

    private void AyoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyoMouseExited
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Start1.png"));
        Ayo.setIcon(II);    
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Mulai.png"));
        Ayo.setIcon(II);
        }
    }//GEN-LAST:event_AyoMouseExited

    private void AyoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyoMousePressed
     
    }//GEN-LAST:event_AyoMousePressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void BtnLoket1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoket1MouseClicked
        if(rs.kosong()) {
            JOptionPane.showMessageDialog(null, "Antrian kosong");
        }
        else {
            lblPanggilNomor1.setText(String.valueOf(rs.getByIndex(0)[0]));
            lblPanggilNama1.setText(String.valueOf(rs.getByIndex(0)[1]));
            lblPanggilAlamat1.setText(String.valueOf(rs.getByIndex(0)[2]));
            rs.dequeue();
            updateTable();
            updateTable2();
            updateTable3();
        }   
    }//GEN-LAST:event_BtnLoket1MouseClicked

    private void BtnLoket2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoket2MouseClicked
        if(rs.kosong()) {
            JOptionPane.showMessageDialog(null, "Antrian kosong");
        }
        else {
            lblPanggilNomor2.setText(String.valueOf(rs.getByIndex(0)[0]));
            lblPanggilNama2.setText(String.valueOf(rs.getByIndex(0)[1]));
            lblPanggilAlamat2.setText(String.valueOf(rs.getByIndex(0)[2]));
            rs.dequeue();
            updateTable();
            updateTable2();
            updateTable3();
        }   
    }//GEN-LAST:event_BtnLoket2MouseClicked

    private void BtnLoket3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoket3MouseClicked
        if(rs.kosong()) {
            JOptionPane.showMessageDialog(null, "Antrian kosong");
        }
        else {
            lblPanggilNomor3.setText(String.valueOf(rs.getByIndex(0)[0]));
            lblPanggilNama3.setText(String.valueOf(rs.getByIndex(0)[1]));
            lblPanggilAlamat3.setText(String.valueOf(rs.getByIndex(0)[2]));
            rs.dequeue();
            updateTable();
            updateTable2();
            updateTable3();
        }   
    }//GEN-LAST:event_BtnLoket3MouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        AnimationClass move = new AnimationClass();
        
        if(t==1){
      //Move Tampilan Utama
      move.jLabelYDown(Background.getY(), 0, 1, 5, Background);
      move.jLabelYDown(Ayo.getY(), 290, 1, 5, Ayo);
      move.jLabelYDown(jLabel10.getY(), 190, 1, 5, jLabel10);
      
      //Move Tampilan 2
      move.jLabelYDown(BackgroundBgt.getY(), 775, 1, 5, BackgroundBgt);
      move.jLabelYDown(BackgroundBgt2.getY(), 775, 1, 5, BackgroundBgt2);
      move.jLabelYDown(ToList.getY(), 1285, 1, 5, ToList);
      move.jLabelYDown(ToList2.getY(), 1425, 1, 5, ToList2);
      move.jLabelYDown(Back.getY(), 965, 1, 5, Back);
      move.jLabelYDown(Kosong.getY(), 1305, 1, 5, Kosong);
      move.jLabelYDown(Daftar.getY(), 1295, 1, 5, Daftar);
      move.jTextFieldYDown(txtNoDaftar.getY(), 1075, 1, 5, txtNoDaftar);
      move.jTextFieldYDown(txtNama.getY(), 1145, 1, 5, txtNama);
      move.jTextFieldYDown(txtAlamat.getY(), 1215, 1, 5, txtAlamat);
      ImageIcon II = new ImageIcon(getClass().getResource("/Button/Mulai2.png"));
        Ayo.setIcon(II);
     
     move.jLabelYDown(BackgroundBtn.getY(), 0, 1, 5, BackgroundBtn);
     move.jLabelYDown(BackgroundTop.getY(), 0, 1, 5, BackgroundTop);
    }
        else if(t==2){
        t=1;
        count=0;
        move.jLabelYDown(BG.getY(), 775, 1, 5, BG);
        move.jLabelYDown(BackgroundAja.getY(), 775, 1, 5, BackgroundAja);
        move.jLabelYDown(ToList.getY(), 510, 1, 5, ToList);
        move.jLabelYDown(ToList2.getY(), 650, 1, 5, ToList2);
        move.jLabelYDown(Back.getY(), 190, 1, 5, Back);
        move.jLabelXRight(Back.getX(), 70, 1, 5, Back);
        move.jLabelYDown(Kosong.getY(), 530, 1, 5, Kosong);
        move.jLabelYDown(Daftar.getY(), 520, 1, 5, Daftar);
        move.jTextFieldYDown(txtNoDaftar.getY(), 300, 1, 5, txtNoDaftar);
        move.jTextFieldYDown(txtNama.getY(), 370, 1, 5, txtNama);
        move.jTextFieldYDown(txtAlamat.getY(), 440, 1, 5, txtAlamat);
        
        move.jLabelYDown(BackgroundBgt.getY(), 0, 1, 5, BackgroundBgt);
        move.jLabelYDown(BackgroundBgt2.getY(), 0, 1, 5, BackgroundBgt2);
        move.jLabelYDown(ToLoket.getY(), 795, 1, 5, ToLoket);
        jScrollPane1.setLocation(185, -2200);
        jScrollPane2.setLocation(322, -2200);
        jScrollPane3.setLocation(590, -2200);
            
        }
        
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Back2.png"));
        Back.setIcon(II);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Back.png"));
        Back.setIcon(II);
    }//GEN-LAST:event_BackMouseExited

    private void ToListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ToListMouseClicked

    private void ToListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToListMouseEntered
        
    }//GEN-LAST:event_ToListMouseEntered

    private void ToListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToListMouseExited
        
    }//GEN-LAST:event_ToListMouseExited

    private void ToList2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToList2MouseEntered
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnToListENG2.png"));
        ToList.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnToList2.png"));
        ToList.setIcon(II);    
        }
    }//GEN-LAST:event_ToList2MouseEntered

    private void ToList2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToList2MouseExited
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnToListENG.png"));
        ToList.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnToList.png"));
        ToList.setIcon(II);    
        }
    }//GEN-LAST:event_ToList2MouseExited

    private void ToList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToList2MouseClicked
        AnimationClass move = new AnimationClass();
        t=2;
        
        move.jLabelYUp(BackgroundAja.getY(), 0, 1, 5, BackgroundAja);
        move.jLabelYUp(BG.getY(), 0, 1, 5, BG);
        move.jLabelYUp(ToList.getY(), -265, 1, 5, ToList);
        move.jLabelYUp(ToList2.getY(), -125, 1, 5, ToList2);
        move.jLabelYUp(Back.getY(), 10, 1, 5, Back);
        move.jLabelXLeft(Back.getX(), 20, 1, 5, Back);
        move.jLabelYUp(Kosong.getY(), -245, 1, 5, Kosong);
        move.jLabelYUp(Daftar.getY(), -255, 1, 5, Daftar);
        move.jTextFieldYUp(txtNoDaftar.getY(), -475, 1, 5, txtNoDaftar);
        move.jTextFieldYUp(txtNama.getY(), -405, 1, 5, txtNama);
        move.jTextFieldYUp(txtAlamat.getY(), -335, 1, 5, txtAlamat);
        
        move.jLabelYUp(BackgroundBgt.getY(), -775, 1, 5, BackgroundBgt);
        move.jLabelYUp(BackgroundBgt2.getY(), -775, 1, 5, BackgroundBgt2);
        move.jLabelYUp(ToLoket.getY(), 20, 1, 5, ToLoket);
        
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/List2.png"));
        BackgroundAja.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/List.png"));
        BackgroundAja.setIcon(II);    
        }
        
        z = new Timer(1000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                count++;
                if(count==1){
                    jScrollPane1.setLocation(185, 220);
                    jScrollPane2.setLocation(322, 220);
                    jScrollPane3.setLocation(590, 220);
                    z.stop();
                }
            }
        });
        z.start();
       
    }//GEN-LAST:event_ToList2MouseClicked

    private void ToLoketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToLoketMouseClicked
        
        lblPanggilNomor1.setVisible(true);
        lblPanggilNomor2.setVisible(true);
        lblPanggilNomor3.setVisible(true);
        lblPanggilNama1.setVisible(true);
        lblPanggilNama2.setVisible(true);
        lblPanggilNama3.setVisible(true);
        lblPanggilAlamat1.setVisible(true);
        lblPanggilAlamat2.setVisible(true);
        lblPanggilAlamat3.setVisible(true);
        BtnLoket1.setVisible(true);
        BtnLoket2.setVisible(true);
        BtnLoket3.setVisible(true);
        Loket1.setVisible(true);
        Loket2.setVisible(true);
        Loket3.setVisible(true);
        BackRahasia.setVisible(true);
        
        ToLoket.setVisible(false);
        jLabel10.setVisible(false);
        Ayo.setVisible(false);
        BackgroundBtn.setVisible(false);
        BackgroundTop.setVisible(false);
        
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Counter.png"));
        Background.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Loket.png"));
        Background.setIcon(II);    
        }
        
    }//GEN-LAST:event_ToLoketMouseClicked

    private void ToLoketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToLoketMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/ToLoket.png"));
        ToLoket.setIcon(II);
    }//GEN-LAST:event_ToLoketMouseExited

    private void ToLoketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToLoketMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/ToLoket2.png"));
        ToLoket.setIcon(II);
    }//GEN-LAST:event_ToLoketMouseEntered

    private void BackRahasiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackRahasiaMouseClicked
            
            t=1;
            count=0;
            
            lblPanggilNomor1.setVisible(false);
            lblPanggilNomor2.setVisible(false);
            lblPanggilNomor3.setVisible(false);
            lblPanggilNama1.setVisible(false);
            lblPanggilNama2.setVisible(false);
            lblPanggilNama3.setVisible(false);
            lblPanggilAlamat1.setVisible(false);
            lblPanggilAlamat2.setVisible(false);
            lblPanggilAlamat3.setVisible(false);
            BtnLoket1.setVisible(false);
            BtnLoket2.setVisible(false);
            BtnLoket3.setVisible(false);
            Loket1.setVisible(false);
            Loket2.setVisible(false);
            Loket3.setVisible(false);
            BackRahasia.setVisible(false);
            
            ToLoket.setVisible(true);
            jLabel10.setVisible(true);
            Ayo.setVisible(true);
            
            jScrollPane1.setLocation(0, 0);
            jScrollPane2.setLocation(0, 0);
            jScrollPane3.setLocation(0, 0);
            
            BackgroundBtn.setVisible(true);
            BackgroundTop.setVisible(true);
            
            if(Bg==1){
            ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/BGutama.png"));
            Background.setIcon(II);
            }
            else if(Bg==2){
            ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Dad1.png"));
            Background.setIcon(II);
            }
            else if(Bg==3){
            ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Alam1.png"));
            Background.setIcon(II);
            }
            else if(Bg==4){
            ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/BalonUdara1.png"));
            Background.setIcon(II);
            }
            else if(Bg==5){
            ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Cake1.png"));
            Background.setIcon(II);
            }
            
    }//GEN-LAST:event_BackRahasiaMouseClicked

    private void BackRahasiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackRahasiaMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Back2.png"));
        BackRahasia.setIcon(II);
    }//GEN-LAST:event_BackRahasiaMouseEntered

    private void BackRahasiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackRahasiaMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Back.png"));
        BackRahasia.setIcon(II);
    }//GEN-LAST:event_BackRahasiaMouseExited

    private void Loket1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loket1MouseEntered
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Counter1.png"));
        Background.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Loket1.png"));
        Background.setIcon(II);    
        }
    }//GEN-LAST:event_Loket1MouseEntered

    private void Loket1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loket1MouseExited
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Counter.png"));
        Background.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Loket.png"));
        Background.setIcon(II);    
        }
    }//GEN-LAST:event_Loket1MouseExited

    private void Loket2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loket2MouseEntered
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Counter2.png"));
        Background.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Loket2.png"));
        Background.setIcon(II);    
        }
    }//GEN-LAST:event_Loket2MouseEntered

    private void Loket2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loket2MouseExited
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Counter.png"));
        Background.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Loket.png"));
        Background.setIcon(II);    
        }
    }//GEN-LAST:event_Loket2MouseExited

    private void Loket3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loket3MouseEntered
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Counter3.png"));
        Background.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Loket3.png"));
        Background.setIcon(II);    
        }
    }//GEN-LAST:event_Loket3MouseEntered

    private void Loket3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loket3MouseExited
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Counter.png"));
        Background.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Loket.png"));
        Background.setIcon(II);    
        }
    }//GEN-LAST:event_Loket3MouseExited

    private void BtnLoket1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoket1MouseEntered
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Counter1.png"));
        Background.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Loket1.png"));
        Background.setIcon(II);    
        }
    }//GEN-LAST:event_BtnLoket1MouseEntered

    private void BtnLoket2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoket2MouseEntered
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Counter2.png"));
        Background.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Loket2.png"));
        Background.setIcon(II);    
        }
    }//GEN-LAST:event_BtnLoket2MouseEntered

    private void BtnLoket3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoket3MouseEntered
        if(B==1){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Counter3.png"));
        Background.setIcon(II);   
        }
        else if(B==2){
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/Loket3.png"));
        Background.setIcon(II);    
        }
    }//GEN-LAST:event_BtnLoket3MouseEntered

    private void BackgroundBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundBtnMouseEntered
        if(s==1){
        ImageIcon IW = new ImageIcon(getClass().getResource("/Button/BtnUpMenu.png"));
        BackgroundBtn.setIcon(IW);
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/MenuButton2.png"));
        BackgroundTop.setIcon(II);
        }
        else if(s==2){
        }
    }//GEN-LAST:event_BackgroundBtnMouseEntered

    private void BackgroundBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundBtnMouseExited
        if(s==1){
        ImageIcon IW = new ImageIcon(getClass().getResource("/Button/BtnMenu.png"));
        BackgroundBtn.setIcon(IW);
        ImageIcon II = new ImageIcon(getClass().getResource("/ImageBackground/MenuButton.png"));
        BackgroundTop.setIcon(II);
        }
        else if(s==2){
        }
        
    }//GEN-LAST:event_BackgroundBtnMouseExited

    private void BackgroundBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundBtnMouseClicked
        AnimationClass move = new AnimationClass();
        if(s==1){
            s=2;
        move.jLabelYDown(Menu.getY(), 0, 1, 10, Menu);
        move.jLabelYDown(BackgroundBtn.getY(), 730, 1, 10, BackgroundBtn);
        move.jLabelYDown(Setting.getY(), 150, 1, 10, Setting);
        move.jLabelYDown(About.getY(), 230, 1, 10, About);
        move.jLabelYDown(Contact.getY(), 310, 1, 10, Contact);
        move.jLabelYDown(Help.getY(), 390, 1, 10, Help);
        move.jLabelYDown(ExitBtn.getY(), 20, 1, 10, ExitBtn);
        }
        if(s==2){
            s=1;
        move.jLabelYUp(Menu.getY(),-775, 1, 10, Menu);
        move.jLabelYUp(BackgroundBtn.getY(), 0, 1, 10, BackgroundBtn);
        }
    }//GEN-LAST:event_BackgroundBtnMouseClicked

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void ExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseEntered
        if(B==1){
         ImageIcon EX = new ImageIcon(getClass().getResource("/Button/ExitBtn2.png"));
        ExitBtn.setIcon(EX);   
        }
        else if(B==2){
         ImageIcon EX = new ImageIcon(getClass().getResource("/Button/Keluar2.png"));
        ExitBtn.setIcon(EX);   
        }        
    }//GEN-LAST:event_ExitBtnMouseEntered

    private void ExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseExited
        if(B==1){
         ImageIcon EX = new ImageIcon(getClass().getResource("/Button/ExitBtn1.png"));
        ExitBtn.setIcon(EX);  
        }
        else if(B==2){
         ImageIcon EX = new ImageIcon(getClass().getResource("/Button/Keluar1.png"));
        ExitBtn.setIcon(EX);   
        }
    }//GEN-LAST:event_ExitBtnMouseExited

    private void HelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseEntered
        if (B==1){
        ImageIcon Hp = new ImageIcon(getClass().getResource("/Button/Help2.png"));
        Help.setIcon(Hp);
        }
        else if (B==2){
        ImageIcon Hp = new ImageIcon(getClass().getResource("/Button/Bantuan2.png"));
        Help.setIcon(Hp);    
        }
    }//GEN-LAST:event_HelpMouseEntered

    private void HelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseExited
        if (B==1){
        ImageIcon Hp = new ImageIcon(getClass().getResource("/Button/Help1.png"));
        Help.setIcon(Hp);
        }
        else if (B==2){
        ImageIcon Hp = new ImageIcon(getClass().getResource("/Button/Bantuan1.png"));
        Help.setIcon(Hp);    
        }
    }//GEN-LAST:event_HelpMouseExited

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
        if (B==1){
        ImageIcon Ab = new ImageIcon(getClass().getResource("/Button/About2.png"));
        About.setIcon(Ab);
        }
        else if (B==2){
        ImageIcon Ab = new ImageIcon(getClass().getResource("/Button/Tentang2.png"));
        About.setIcon(Ab);    
        }
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
        if (B==1){
        ImageIcon Ab = new ImageIcon(getClass().getResource("/Button/About1.png"));
        About.setIcon(Ab);
        }
        else if (B==2){
        ImageIcon Ab = new ImageIcon(getClass().getResource("/Button/Tentang1.png"));
        About.setIcon(Ab);
        }
    }//GEN-LAST:event_AboutMouseExited

    private void ContactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactMouseEntered
        if (B==1){
        ImageIcon Co = new ImageIcon(getClass().getResource("/Button/Contact2.png"));
        Contact.setIcon(Co);
        }
        else if (B==2){
        ImageIcon Co = new ImageIcon(getClass().getResource("/Button/Kontak2.png"));
        Contact.setIcon(Co);    
        }
    }//GEN-LAST:event_ContactMouseEntered

    private void ContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactMouseClicked
        Contact cntk = new Contact();
        cntk.setVisible(true);
    }//GEN-LAST:event_ContactMouseClicked

    private void SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseEntered
        if (B==1){
        ImageIcon St = new ImageIcon(getClass().getResource("/Button/Settting2.png"));
        Setting.setIcon(St);
        }
        else if (B==2){
        ImageIcon St = new ImageIcon(getClass().getResource("/Button/Pengaturan2.png"));
        Setting.setIcon(St);    
        }
    }//GEN-LAST:event_SettingMouseEntered

    private void SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseExited
        if (B==1){
        ImageIcon St = new ImageIcon(getClass().getResource("/Button/Settting1.png"));
        Setting.setIcon(St);
        }
        else if (B==2){
        ImageIcon St = new ImageIcon(getClass().getResource("/Button/Pengaturan1.png"));
        Setting.setIcon(St);
        
        }
    }//GEN-LAST:event_SettingMouseExited

    private void ContactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactMouseExited
        if (B==1){
        ImageIcon Co = new ImageIcon(getClass().getResource("/Button/Contact1.png"));
        Contact.setIcon(Co);
        }
        else if (B==2){
        ImageIcon Co = new ImageIcon(getClass().getResource("/Button/Kontak1.png"));
        Contact.setIcon(Co);    
        
        }
    }//GEN-LAST:event_ContactMouseExited

    private void SettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseClicked
        AnimationClass move = new AnimationClass();
   
        move.jLabelXRight(ChangeBackground.getX(), 0, 1, 5, ChangeBackground);
        move.jLabelXRight(ChangeLanguage.getX(), 0, 1, 5, ChangeLanguage);
        move.jLabelYDown(Kembali.getY(), 20, 1, 5, Kembali);
       
    }//GEN-LAST:event_SettingMouseClicked

    private void ChangeBackgroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeBackgroundMouseEntered
        if (B==1){
        ImageIcon CBa = new ImageIcon(getClass().getResource("/ImageBackground/ChangeBackground2.png"));
        ChangeBackground.setIcon(CBa);
        }
        else if (B==2){
        ImageIcon CBa = new ImageIcon(getClass().getResource("/ImageBackground/GantiLatarBelakang2.png"));
        ChangeBackground.setIcon(CBa);    
        }
    }//GEN-LAST:event_ChangeBackgroundMouseEntered

    private void ChangeBackgroundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeBackgroundMouseExited
        if (B==1){
        ImageIcon CBa = new ImageIcon(getClass().getResource("/ImageBackground/ChangeBackground1.png"));
        ChangeBackground.setIcon(CBa);
        }
        else if (B==2){
        ImageIcon CBa = new ImageIcon(getClass().getResource("/ImageBackground/GantiLatarBelakang1.png"));
        ChangeBackground.setIcon(CBa);
        
        }
    }//GEN-LAST:event_ChangeBackgroundMouseExited

    private void ChangeLanguageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeLanguageMouseEntered
        if (B==1){
        ImageIcon CLa = new ImageIcon(getClass().getResource("/ImageBackground/ChangeLanguage2.png"));
        ChangeLanguage.setIcon(CLa);
        }
        else if (B==2){
        ImageIcon CLa = new ImageIcon(getClass().getResource("/ImageBackground/GantiBahasa2.png"));
        ChangeLanguage.setIcon(CLa);    
        }
    }//GEN-LAST:event_ChangeLanguageMouseEntered

    private void ChangeLanguageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeLanguageMouseExited
        if (B==1){
        ImageIcon CLa = new ImageIcon(getClass().getResource("/ImageBackground/ChangeLanguage1.png"));
        ChangeLanguage.setIcon(CLa);
        }
        else if (B==2){
        ImageIcon CLa = new ImageIcon(getClass().getResource("/ImageBackground/GantiBahasa1.png"));
        ChangeLanguage.setIcon(CLa);    
        
        }
    }//GEN-LAST:event_ChangeLanguageMouseExited

    private void KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseClicked
       AnimationClass move = new AnimationClass();
   if(K==1){
        move.jLabelXLeft(ChangeBackground.getX(), -400, 1, 5, ChangeBackground);
        move.jLabelXLeft(ChangeLanguage.getX(), -400, 1, 5, ChangeLanguage);
        move.jLabelYUp(Kembali.getY(), -60, 1, 5, Kembali);
   }
   else if(K==2){
        move.jLabelYUp(INA.getY(), -300, 1, 10, INA);
        move.jLabelYUp(ENG.getY(), -300, 1, 10, ENG);
        move.jLabelXLeft(Kembali.getX(), 400, 1, 10, Kembali);
        move.jLabelXLeft(Temp.getX(), -800, 1, 10, Temp);
        move.jLabelYUp(BG1.getY(), -100, 1, 5, BG1);
        move.jLabelYUp(BG2.getY(), -100, 1, 5, BG2);
        move.jLabelYUp(BG3.getY(), -100, 1, 5, BG3);
        move.jLabelYUp(BG4.getY(), -100, 1, 5, BG4);
        move.jLabelYUp(BG5.getY(), -100, 1, 5, BG5);
        K=1;
   }
    }//GEN-LAST:event_KembaliMouseClicked

    private void KembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseEntered
        ImageIcon KB = new ImageIcon(getClass().getResource("/Button/Kembali2.png"));
        Kembali.setIcon(KB);
    }//GEN-LAST:event_KembaliMouseEntered

    private void KembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseExited
        ImageIcon KB = new ImageIcon(getClass().getResource("/Button/Kembali1.png"));
        Kembali.setIcon(KB);
    }//GEN-LAST:event_KembaliMouseExited

    private void ChangeLanguageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeLanguageMouseClicked
        AnimationClass move = new AnimationClass();
   if(K==1){
        move.jLabelYDown(INA.getY(), 0, 1, 10, INA);
        move.jLabelYDown(ENG.getY(), 300, 1, 10, ENG);
        move.jLabelXRight(Kembali.getX(), 820, 1, 10, Kembali);
        move.jLabelXRight(Temp.getX(), -150, 1, 10, Temp);
        K=2;
   }
   else if(K==2){
       
        move.jLabelXLeft(Kembali.getX(), 400, 1, 10, Kembali);
        move.jLabelXLeft(Temp.getX(), -800, 1, 10, Temp);
        move.jLabelYUp(BG1.getY(), -100, 1, 5, BG1);
        move.jLabelYUp(BG2.getY(), -100, 1, 5, BG2);
        move.jLabelYUp(BG3.getY(), -100, 1, 5, BG3);
        move.jLabelYUp(BG4.getY(), -100, 1, 5, BG4);
        move.jLabelYUp(BG5.getY(), -100, 1, 5, BG5);
        
        move.jLabelYUp(INA.getY(), -300, 1, 10, INA);
        move.jLabelYUp(ENG.getY(), -300, 1, 10, ENG);
        
        K=1;
   }
   
    }//GEN-LAST:event_ChangeLanguageMouseClicked

    private void INAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INAMouseClicked
        B=2;
        ImageIcon CLa = new ImageIcon(getClass().getResource("/ImageBackground/GantiBahasa1.png"));
        ChangeLanguage.setIcon(CLa);    
        ImageIcon CBa = new ImageIcon(getClass().getResource("/ImageBackground/GantiLatarBelakang1.png"));
        ChangeBackground.setIcon(CBa);
        ImageIcon Co = new ImageIcon(getClass().getResource("/Button/Kontak1.png"));
        Contact.setIcon(Co);    
        ImageIcon St = new ImageIcon(getClass().getResource("/Button/Pengaturan1.png"));
        Setting.setIcon(St);
        ImageIcon Ab = new ImageIcon(getClass().getResource("/Button/Tentang1.png"));
        About.setIcon(Ab);
        ImageIcon Hp = new ImageIcon(getClass().getResource("/Button/Bantuan1.png"));
        Help.setIcon(Hp);
        ImageIcon J10 = new ImageIcon(getClass().getResource("/Button/Mengantri.png"));
        jLabel10.setIcon(J10);
        ImageIcon Ay = new ImageIcon(getClass().getResource("/Button/Mulai.png"));
        Ayo.setIcon(Ay);
        ImageIcon Kl = new ImageIcon(getClass().getResource("/Button/Keluar1.png"));
        ExitBtn.setIcon(Kl);
        ImageIcon EN = new ImageIcon(getClass().getResource("/ImageBackground/Inggris1.png"));
        ENG.setIcon(EN);    
        ImageIcon IN = new ImageIcon(getClass().getResource("/ImageBackground/Indonesia1.png"));
        INA.setIcon(IN);
        ImageIcon IK = new ImageIcon(getClass().getResource("/ImageBackground/DaftarTemp.png"));
        BackgroundBgt.setIcon(IK);
        ImageIcon BA = new ImageIcon(getClass().getResource("/ImageBackground/List.png"));
        BackgroundAja.setIcon(BA);
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnDaftar.png"));
        Daftar.setIcon(II);
        ImageIcon Ia = new ImageIcon(getClass().getResource("/Button/Kosong.png"));
        Kosong.setIcon(Ia);
        ImageIcon Iw = new ImageIcon(getClass().getResource("/Button/BtnToList.png"));
        ToList.setIcon(Iw);
        ImageIcon B1 = new ImageIcon(getClass().getResource("/ImageBackground/BGutama1INA.png"));
        BG1.setIcon(B1);
        ImageIcon B2 = new ImageIcon(getClass().getResource("/ImageBackground/Dad1INA.png"));
        BG2.setIcon(B2);
        ImageIcon B3 = new ImageIcon(getClass().getResource("/ImageBackground/Alam1INA.png"));
        BG3.setIcon(B3);
        ImageIcon B4 = new ImageIcon(getClass().getResource("/ImageBackground/BalonUdara1INA.png"));
        BG4.setIcon(B4);
        ImageIcon B5 = new ImageIcon(getClass().getResource("/ImageBackground/Cake1INA.png"));
        BG5.setIcon(B5);        
    }//GEN-LAST:event_INAMouseClicked

    private void INAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INAMouseEntered
        if (B==1){
        ImageIcon IN = new ImageIcon(getClass().getResource("/ImageBackground/Indonesian2.png"));
        INA.setIcon(IN);
        }
        else if (B==2){
        ImageIcon IN = new ImageIcon(getClass().getResource("/ImageBackground/Indonesia2.png"));
        INA.setIcon(IN);    
        }
    }//GEN-LAST:event_INAMouseEntered

    private void INAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INAMouseExited
       if (B==1){
        ImageIcon IN = new ImageIcon(getClass().getResource("/ImageBackground/Indonesian1.png"));
        INA.setIcon(IN);
        }
        else if (B==2){
        ImageIcon IN = new ImageIcon(getClass().getResource("/ImageBackground/Indonesia1.png"));
        INA.setIcon(IN);    
        }
    }//GEN-LAST:event_INAMouseExited

    private void ENGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENGMouseClicked
        B=1;
        ImageIcon CLa = new ImageIcon(getClass().getResource("/ImageBackground/ChangeLanguage1.png"));
        ChangeLanguage.setIcon(CLa);    
        ImageIcon CBa = new ImageIcon(getClass().getResource("/ImageBackground/ChangeBackground1.png"));
        ChangeBackground.setIcon(CBa);
        ImageIcon Co = new ImageIcon(getClass().getResource("/Button/Contact1.png"));
        Contact.setIcon(Co);      
        ImageIcon St = new ImageIcon(getClass().getResource("/Button/Settting1.png"));
        Setting.setIcon(St);
        ImageIcon Ab = new ImageIcon(getClass().getResource("/Button/About1.png"));
        About.setIcon(Ab);
        ImageIcon Hp = new ImageIcon(getClass().getResource("/Button/Help1.png"));
        Help.setIcon(Hp);
        ImageIcon J10 = new ImageIcon(getClass().getResource("/Button/Mengantri2.png"));
        jLabel10.setIcon(J10);
        ImageIcon Ay = new ImageIcon(getClass().getResource("/Button/Start1.png"));
        Ayo.setIcon(Ay);
        ImageIcon Kl = new ImageIcon(getClass().getResource("/Button/ExitBtn1.png"));
        ExitBtn.setIcon(Kl);
        ImageIcon EN = new ImageIcon(getClass().getResource("/ImageBackground/English1.png"));
        ENG.setIcon(EN);    
        ImageIcon IN = new ImageIcon(getClass().getResource("/ImageBackground/Indonesian1.png"));
        INA.setIcon(IN);
        ImageIcon IK = new ImageIcon(getClass().getResource("/ImageBackground/DaftarTemp2.png"));
        BackgroundBgt.setIcon(IK);
        ImageIcon BA = new ImageIcon(getClass().getResource("/ImageBackground/List2.png"));
        BackgroundAja.setIcon(BA);
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/BtnRegister.png"));
        Daftar.setIcon(II);
        ImageIcon Ia = new ImageIcon(getClass().getResource("/Button/Delete.png"));
        Kosong.setIcon(Ia);
        ImageIcon Iw = new ImageIcon(getClass().getResource("/Button/BtnToListENG.png"));
        ToList.setIcon(Iw);
         ImageIcon B1 = new ImageIcon(getClass().getResource("/ImageBackground/BGutama1.png"));
        BG1.setIcon(B1);
        ImageIcon B2 = new ImageIcon(getClass().getResource("/ImageBackground/Dad1ENG.png"));
        BG2.setIcon(B2);
        ImageIcon B3 = new ImageIcon(getClass().getResource("/ImageBackground/Alam1ENG.png"));
        BG3.setIcon(B3);
        ImageIcon B4 = new ImageIcon(getClass().getResource("/ImageBackground/BalonUdara1ENG.png"));
        BG4.setIcon(B4);
        ImageIcon B5 = new ImageIcon(getClass().getResource("/ImageBackground/Cake1ENG.png"));
        BG5.setIcon(B5);
    }//GEN-LAST:event_ENGMouseClicked

    private void ENGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENGMouseEntered
        if (B==1){
        ImageIcon EN = new ImageIcon(getClass().getResource("/ImageBackground/English2.png"));
        ENG.setIcon(EN);
        }
        else if (B==2){
        ImageIcon EN = new ImageIcon(getClass().getResource("/ImageBackground/Inggris2.png"));
        ENG.setIcon(EN);    
        }
    }//GEN-LAST:event_ENGMouseEntered

    private void ENGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENGMouseExited
        if (B==1){
        ImageIcon EN = new ImageIcon(getClass().getResource("/ImageBackground/English1.png"));
        ENG.setIcon(EN);
        }
        else if (B==2){
        ImageIcon EN = new ImageIcon(getClass().getResource("/ImageBackground/Inggris1.png"));
        ENG.setIcon(EN);    
        }
    }//GEN-LAST:event_ENGMouseExited

    private void ChangeBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeBackgroundMouseClicked
        AnimationClass move = new AnimationClass();
    if(K==1){  
        move.jLabelYDown(BG1.getY(), 0, 1, 5, BG1);
        move.jLabelYDown(BG2.getY(), 100, 1, 5, BG2);
        move.jLabelYDown(BG3.getY(), 200, 1, 5, BG3);
        move.jLabelYDown(BG4.getY(), 300, 1, 5, BG4);
        move.jLabelYDown(BG5.getY(), 400, 1, 5, BG5);
        move.jLabelXRight(Temp.getX(), 110, 1, 10, Temp);
        move.jLabelXRight(Kembali.getX(), 950, 1, 10, Kembali);
        
        K=2;
    }
    else if (K==2){
        
        move.jLabelYUp(INA.getY(), -300, 1, 10, INA);
        move.jLabelYUp(ENG.getY(), -300, 1, 10, ENG);
        move.jLabelXLeft(Kembali.getX(), 400, 1, 10, Kembali);
        move.jLabelXLeft(Temp.getX(), -800, 1, 10, Temp);
        
        move.jLabelYUp(BG1.getY(), -100, 1, 5, BG1);
        move.jLabelYUp(BG2.getY(), -100, 1, 5, BG2);
        move.jLabelYUp(BG3.getY(), -100, 1, 5, BG3);
        move.jLabelYUp(BG4.getY(), -100, 1, 5, BG4);
        move.jLabelYUp(BG5.getY(), -100, 1, 5, BG5);
        
        K=1;
    }
    }//GEN-LAST:event_ChangeBackgroundMouseClicked

    private void BackgroundBgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundBgtMouseClicked
        
    }//GEN-LAST:event_BackgroundBgtMouseClicked

    private void BG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG1MouseClicked
        ImageIcon Bg1 = new ImageIcon(getClass().getResource("/ImageBackground/BGutama.png"));
        Background.setIcon(Bg1);
        ImageIcon Bg2 = new ImageIcon(getClass().getResource("/ImageBackground/Artboard 1.png"));
        BackgroundBgt2.setIcon(Bg2);
        ImageIcon Bg3 = new ImageIcon(getClass().getResource("/ImageBackground/Artboard 1.png"));
        BG.setIcon(Bg3);
        Bg=1;
    }//GEN-LAST:event_BG1MouseClicked

    private void BG1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG1MouseEntered
        if (B==1){
        ImageIcon B1 = new ImageIcon(getClass().getResource("/ImageBackground/BGutama2.png"));
        BG1.setIcon(B1);
        }
        else if (B==2){
        ImageIcon B1 = new ImageIcon(getClass().getResource("/ImageBackground/BGutama2INA.png"));
        BG1.setIcon(B1);
        
        }
    }//GEN-LAST:event_BG1MouseEntered

    private void BG1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG1MouseExited
        if (B==1){
        ImageIcon B1 = new ImageIcon(getClass().getResource("/ImageBackground/BGutama1.png"));
        BG1.setIcon(B1);
        }
        else if (B==2){
        ImageIcon B1 = new ImageIcon(getClass().getResource("/ImageBackground/BGutama1INA.png"));
        BG1.setIcon(B1);
        
        }
    }//GEN-LAST:event_BG1MouseExited

    private void BG2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG2MouseClicked
        ImageIcon Bg1 = new ImageIcon(getClass().getResource("/ImageBackground/Dad1.png"));
        Background.setIcon(Bg1);
        ImageIcon Bg2 = new ImageIcon(getClass().getResource("/ImageBackground/Dad2.png"));
        BackgroundBgt2.setIcon(Bg2);
        ImageIcon Bg3 = new ImageIcon(getClass().getResource("/ImageBackground/Dad2.png"));
        BG.setIcon(Bg3);
        Bg=2;
    }//GEN-LAST:event_BG2MouseClicked

    private void BG2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG2MouseEntered
        if (B==1){
        ImageIcon B2 = new ImageIcon(getClass().getResource("/ImageBackground/Dad2ENG.png"));
        BG2.setIcon(B2);
        }
        else if (B==2){
        ImageIcon B2 = new ImageIcon(getClass().getResource("/ImageBackground/Dad2INA.png"));
        BG2.setIcon(B2);
        }
    }//GEN-LAST:event_BG2MouseEntered

    private void BG2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG2MouseExited
       if (B==1){
        ImageIcon B2 = new ImageIcon(getClass().getResource("/ImageBackground/Dad1ENG.png"));
        BG2.setIcon(B2);
        }
        else if (B==2){
        ImageIcon B2 = new ImageIcon(getClass().getResource("/ImageBackground/Dad1INA.png"));
        BG2.setIcon(B2);
        }
    }//GEN-LAST:event_BG2MouseExited

    private void BG3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG3MouseClicked
        ImageIcon Bg1 = new ImageIcon(getClass().getResource("/ImageBackground/Alam1.png"));
        Background.setIcon(Bg1);
        ImageIcon Bg2 = new ImageIcon(getClass().getResource("/ImageBackground/Alam2.png"));
        BackgroundBgt2.setIcon(Bg2);
        ImageIcon Bg3 = new ImageIcon(getClass().getResource("/ImageBackground/Alam2.png"));
        BG.setIcon(Bg3);
        Bg=3;
    }//GEN-LAST:event_BG3MouseClicked

    private void BG3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG3MouseEntered
        if (B==1){
        ImageIcon B3 = new ImageIcon(getClass().getResource("/ImageBackground/Alam2ENG.png"));
        BG3.setIcon(B3);
        }
        else if (B==2){
        ImageIcon B3 = new ImageIcon(getClass().getResource("/ImageBackground/Alam2INA.png"));
        BG3.setIcon(B3);
        }
    }//GEN-LAST:event_BG3MouseEntered

    private void BG3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG3MouseExited
        if (B==1){
        ImageIcon B3 = new ImageIcon(getClass().getResource("/ImageBackground/Alam1ENG.png"));
        BG3.setIcon(B3);
        }
        else if (B==2){
        ImageIcon B3 = new ImageIcon(getClass().getResource("/ImageBackground/Alam1INA.png"));
        BG3.setIcon(B3);
        }
    }//GEN-LAST:event_BG3MouseExited

    private void BG4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG4MouseClicked
        ImageIcon Bg1 = new ImageIcon(getClass().getResource("/ImageBackground/BalonUdara1.png"));
        Background.setIcon(Bg1);
        ImageIcon Bg2 = new ImageIcon(getClass().getResource("/ImageBackground/BalonUdara2.png"));
        BackgroundBgt2.setIcon(Bg2);
        ImageIcon Bg3 = new ImageIcon(getClass().getResource("/ImageBackground/BalonUdara2.png"));
        BG.setIcon(Bg3);
        Bg=4;
    }//GEN-LAST:event_BG4MouseClicked

    private void BG4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG4MouseEntered
        if (B==1){
        ImageIcon B4 = new ImageIcon(getClass().getResource("/ImageBackground/BalonUdara2ENG.png"));
        BG4.setIcon(B4);
        }
        else if (B==2){
        ImageIcon B4 = new ImageIcon(getClass().getResource("/ImageBackground/BalonUdara2INA.png"));
        BG4.setIcon(B4);
        }
    }//GEN-LAST:event_BG4MouseEntered

    private void BG4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG4MouseExited
        if (B==1){
        ImageIcon B4 = new ImageIcon(getClass().getResource("/ImageBackground/BalonUdara1ENG.png"));
        BG4.setIcon(B4);
        }
        else if (B==2){
        ImageIcon B4 = new ImageIcon(getClass().getResource("/ImageBackground/BalonUdara1INA.png"));
        BG4.setIcon(B4);
        }
    }//GEN-LAST:event_BG4MouseExited

    private void BG5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG5MouseClicked
        ImageIcon Bg1 = new ImageIcon(getClass().getResource("/ImageBackground/Cake1.png"));
        Background.setIcon(Bg1);
        ImageIcon Bg2 = new ImageIcon(getClass().getResource("/ImageBackground/Cake2.png"));
        BackgroundBgt2.setIcon(Bg2);
        ImageIcon Bg3 = new ImageIcon(getClass().getResource("/ImageBackground/Cake2.png"));
        BG.setIcon(Bg3);
        Bg=5;
    }//GEN-LAST:event_BG5MouseClicked

    private void BG5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG5MouseEntered
        if (B==1){
        ImageIcon B5 = new ImageIcon(getClass().getResource("/ImageBackground/Cake2ENG.png"));
        BG5.setIcon(B5);
        }
        else if (B==2){
        ImageIcon B5 = new ImageIcon(getClass().getResource("/ImageBackground/Cake2INA.png"));
        BG5.setIcon(B5);
        }
    }//GEN-LAST:event_BG5MouseEntered

    private void BG5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG5MouseExited
        if (B==1){
        ImageIcon B5 = new ImageIcon(getClass().getResource("/ImageBackground/Cake1ENG.png"));
        BG5.setIcon(B5);
        }
        else if (B==2){
        ImageIcon B5 = new ImageIcon(getClass().getResource("/ImageBackground/Cake1INA.png"));
        BG5.setIcon(B5);
        }
    }//GEN-LAST:event_BG5MouseExited

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_AboutMouseClicked

    private void HelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseClicked
       Help p = new Help();
       p.setVisible(true);
    }//GEN-LAST:event_HelpMouseClicked

    public void clearTable() {
        DefaultTableModel dataModel = (DefaultTableModel) tbAntrian.getModel();
        dataModel.setRowCount(0);
    }
    
    public void updateTable() {
        clearTable();
        DefaultTableModel dataModel = (DefaultTableModel) tbAntrian.getModel();
        Object[] list = new Object[1];
        for(int i=0; i<rs.idxAkhir; i++) {
            list[0] = rs.getByIndex(i)[0];
            dataModel.addRow(list);
        }
    }
    public void clearTable2() {
        DefaultTableModel dataModel = (DefaultTableModel) tbAntrian1.getModel();
        dataModel.setRowCount(0);
    }
    
    public void updateTable2() {
        clearTable2();
        DefaultTableModel dataModel = (DefaultTableModel) tbAntrian1.getModel();
        Object[] list = new Object[1];
        for(int i=0; i<rs.idxAkhir; i++) {
            list[0] = rs.getByIndex(i)[1];
            dataModel.addRow(list);
        }
    }
    public void clearTable3() {
        DefaultTableModel dataModel = (DefaultTableModel) tbAntrian2.getModel();
        dataModel.setRowCount(0);
    }
    
    public void updateTable3() {
        clearTable3();
        DefaultTableModel dataModel = (DefaultTableModel) tbAntrian2.getModel();
        Object[] list = new Object[1];
        for(int i=0; i<rs.idxAkhir; i++) {
            list[0] = rs.getByIndex(i)[2];
            dataModel.addRow(list);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Queue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Queue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Queue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Queue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Queue1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JLabel Ayo;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel BG1;
    private javax.swing.JLabel BG2;
    private javax.swing.JLabel BG3;
    private javax.swing.JLabel BG4;
    private javax.swing.JLabel BG5;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel BackRahasia;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BackgroundAja;
    private javax.swing.JLabel BackgroundBgt;
    private javax.swing.JLabel BackgroundBgt2;
    private javax.swing.JLabel BackgroundBtn;
    private javax.swing.JLabel BackgroundTop;
    private javax.swing.JLabel BtnLoket1;
    private javax.swing.JLabel BtnLoket2;
    private javax.swing.JLabel BtnLoket3;
    private javax.swing.JLabel ChangeBackground;
    private javax.swing.JLabel ChangeLanguage;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Daftar;
    private javax.swing.JLabel ENG;
    private javax.swing.JLabel ExitBtn;
    private javax.swing.JLabel Help;
    private javax.swing.JLabel INA;
    private javax.swing.JLabel Kembali;
    private javax.swing.JLabel Kosong;
    private javax.swing.JLabel Loket1;
    private javax.swing.JLabel Loket2;
    private javax.swing.JLabel Loket3;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Setting;
    private javax.swing.JLabel Temp;
    private javax.swing.JLabel ToList;
    private javax.swing.JLabel ToList2;
    private javax.swing.JLabel ToLoket;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblPanggilAlamat1;
    private javax.swing.JLabel lblPanggilAlamat2;
    private javax.swing.JLabel lblPanggilAlamat3;
    private javax.swing.JLabel lblPanggilNama1;
    private javax.swing.JLabel lblPanggilNama2;
    private javax.swing.JLabel lblPanggilNama3;
    private javax.swing.JLabel lblPanggilNomor1;
    private javax.swing.JLabel lblPanggilNomor2;
    private javax.swing.JLabel lblPanggilNomor3;
    private javax.swing.JTable tbAntrian;
    private javax.swing.JTable tbAntrian1;
    private javax.swing.JTable tbAntrian2;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoDaftar;
    // End of variables declaration//GEN-END:variables
}
